const WordList = [
    { word: "elephant", hint: "The largest land animal" },
    { word: "computer", hint: "A programmable electronic device" },
    { word: "ocean", hint: "A large body of salt water" },
    { word: "telescope", hint: "A tool used to look at stars" },
    { word: "volcano", hint: "A mountain that can erupt" },
    { word: "bicycle", hint: "A vehicle with two wheels" },
    { word: "bridge", hint: "A structure built to span physical obstacles" },
    { word: "chocolate", hint: "A sweet, brown food made from roasted cacao seeds" },
    { word: "jazz", hint: "A music genre that originated in the African-American communities" },
    { word: "pyramid", hint: "A monumental structure with a square or triangular base and sloping sides" },
    { word: "unicorn", hint: "A mythical animal typically represented as a horse with a single straight horn projecting from its forehead" },
    { word: "vaccine", hint: "A substance used to stimulate the production of antibodies and provide immunity against one or several diseases" },
    { word: "waterfall", hint: "A cascade of water falling from a height, formed when a river or stream flows over a precipice or steep incline" },
    { word: "xylophone", hint: "A musical instrument played by striking a row of wooden bars of graduated length with one or more small wooden or plastic beaters" },
    { word: "yacht", hint: "A medium-sized sailboat equipped for cruising or racing" },
    { word: "zeppelin", hint: "A type of rigid airship named after the German inventor who designed it" },
    { word: "acrylic", hint: "A synthetic material used for paints and other applications" },
    { word: "blimp", hint: "A small, non-rigid airship" },
    { word: "cryptic", hint: "Having a meaning that is mysterious or obscure" },
    { word: "dystopia", hint: "An imagined state or society in which there is great suffering or injustice" },
    { word: "euphoria", hint: "A feeling or state of intense excitement and happiness" },
    { word: "fjord", hint: "A long, narrow, deep inlet of the sea between high cliffs" },
    { word: "genome", hint: "The complete set of genes or genetic material present in a cell or organism" },
    { word: "horoscope", hint: "A forecast of a person's future, typically including a delineation of character and circumstances, based on the relative positions of the stars and planets at the time of that person's birth" },
    { word: "infrared", hint: "A type of electromagnetic radiation invisible to the human eye" },
    { word: "juxtapose", hint: "To place or deal with close together for contrasting effect" },
    { word: "kaleidoscope", hint: "A toy consisting of a tube containing mirrors and pieces of colored glass or paper, whose reflections produce changing patterns that are visible through an eyehole when the tube is rotated" },
    { word: "loquacious", hint: "Tending to talk a great deal; talkative" },
    { word: "metaphor", hint: "A figure of speech in which a word or phrase is applied to an object or action to which it is not literally applicable" },
    { word: "narcissism", hint: "Excessive interest in or admiration of oneself and one's physical appearance" },
    { word: "oscillate", hint: "To move or swing back and forth at a regular speed" },
    { word: "paradox", hint: "A seemingly absurd or self-contradictory statement or proposition that when investigated may prove to be well founded or true" },
    { word: "quasar", hint: "A massive and extremely remote celestial object, emitting exceptionally large amounts of energy, and typically having a star-like image in a telescope" },
    { word: "rhetoric", hint: "The art of effective or persuasive speaking or writing, especially the use of figures of speech and other compositional techniques" },
    { word: "symbiosis", hint: "Interaction between two different organisms living in close physical association, typically to the advantage of both" },
    { word: "turbulence", hint: "Violent or unsteady movement of air or water, or of some other fluid" },
    { word: "utopia", hint: "An imagined place or state of things in which everything is perfect" },
    { word: "vortex", hint: "A mass of whirling fluid or air, especially a whirlpool or whirlwind" },
    { word: "wavelength", hint: "The distance between successive crests of a wave, especially points in a sound wave or electromagnetic wave" },
    { word: "xenophobia", hint: "Dislike of or prejudice against people from other countries" },
    { word: "yield", hint: "To produce or provide (a natural, agricultural, or industrial product)" },
    { word: "zenith", hint: "The time at which something is most powerful or successful" }
];

export default WordList;